version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:

  checking__manware:  
    executor:
      name: android/android-machine
    parallelism: 4

    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y libgbm-dev
      - run: npm i -s
      - run: node app.js

workflows:

  sample: 
    jobs:
      - checking__manware
